### ISSUE TITLE
Add ability to set Domain policy

### ISSUE THREAD

**Issue by alexanderpolson** [walmsles/cdk-codeartifact#10]
The construct doesn't yet have an API to apply a policy to it.

**Comment by walmsles** [comment]
The CodeartifactProps are setup to extend the existing CfnDomainProps - so the actual data property is available for setting the "permissionsPolicyDocument".   So this should be naturally available in all versions.

With the refactoring around #9, I am making the Props more aptly named and more explicit, so the attributes are more obvious (and the fact recent jsii updates do not like interfaces/structs being extended)

**Comment by walmsles** [comment]
Closing as API is available but just not obvious in the code today.  As part of #9 refactor DomainProps will be more explicitly defined by the package.
