### ISSUE TITLE
Rename CodeArtifact construct to Domain so its intention is clearer

### ISSUE THREAD

**Issue by alexanderpolson** [walmsles/cdk-codeartifact#9]
The CodeArtifact name isn't specific enough to make its intention clear. It should be renamed to Domain to make it clearer and consistent with the L1 Construct.

**Comment by alexanderpolson** [comment]
The same naming convention should be extended to [CodeArtifactProps](https://github.com/walmsles/cdk-codeartifact/blob/main/src/types.ts#L62).

**Comment by walmsles** [comment]
Hi @alexanderpolson thanks for raising this issue.  I agree with your comment regarding intent.  I am refactoring to enable backward compatibility and marking the CodeArtifact classes as deprecated for clarity.  

I originally had a different vision for this construct at the start, but it became clear to me that what I originally planned would not be possible as I progressed.  I think there is still some utility and convenience within this construct that provides value.

**Comment by walmsles** [comment]
Resolved in release v1.0.1
